# config.yaml
paths:
  rgb_img_path: "/Users/mackenziesnyder/Desktop/Capstone/wAI/data/img_6.png"
  depth_img_path: "/Users/mackenziesnyder/Desktop/Capstone/wAI/data/img_6.npy"
  pt_cloud_ply_path: "/Users/mackenziesnyder/Desktop/Capstone/wAI/3D-processing/point_cloud.ply"
  sam_pt_cloud_ply_path: "/Users/mackenziesnyder/Desktop/Capstone/wAI/3D-processing/sam_point_cloud.ply"
  sam3d_model_checkpoint: '/Users/mackenziesnyder/Desktop/Capstone/wAI/3D-processing/modelling/sam-3d-body/checkpoints/sam-3d-body-dinov3/model.ckpt'
  mhr_model_checkpoint: '/Users/mackenziesnyder/Desktop/Capstone/wAI/3D-processing/modelling/sam-3d-body/checkpoints/sam-3d-body-dinov3/assets/mhr_model.pt'

camera:
fx: 638.19
fy: 639.70
cx: 356.18
cy: 246.72323964

inputs:
  sex: "Female" # "Female" or "Male"
  height: 160 # in cm, optional
