# config.yaml
paths:
  rgb_img_path: "/Users/adeleyounis/Desktop/Capstone/data/realsense_data/01_20_2026/input/alexis_rgb.png"
  depth_img_path: "/Users/adeleyounis/Desktop/Capstone/data/realsense_data/01_20_2026/input/alexis_depth.npy"
  pt_cloud_ply_path: "/Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/point_cloud.ply"
  sam_pt_cloud_ply_path: "/Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/sam_point_cloud.ply"
  sam3d_model_checkpoint: '/Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/modelling/sam-3d/checkpoints/sam-3d-body-dinov3/model.ckpt'
  mhr_model_checkpoint: '/Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/modelling/sam-3d/checkpoints/sam-3d-body-dinov3/assets/mhr_model.pt'

  # archived
  pt_cloud_txt_path: "output/pointcloud.txt"
  smplx_model_path: '/Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/modelling/models/smplx'
  vposer_model_path: /Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/modelling/models/vposer_v1_0'
  pixie_dir: '/Users/adeleyounis/Desktop/Capstone/wAI/3D-processing/modelling/models/PIXIE'
  openpose_path: "posture-estimator/human-pose-estimation-opencv/openpose.py"
  pose_output_dir: 'output/'
  pose_estimator_nn_path: "posture-estimator/human-pose-estimation-opencv/graph_opt.pb"
 
camera:
  fx: 615.70
  fy: 615.71
  cx: 330.00
  cy: 239.04

inputs:
  sex: "Female" # "Female" or "Male"
  height: 165 # in cm, optional
