# config.yaml
paths:
  rgb_img_path: "C:/Users/wai/wAI/data/20260120_143300_rgb.png"
  depth_img_path: "C:/Users/wai/wAI/data/20260120_143300_depth.npy"
  pt_cloud_ply_path: "C:/Users/wai/wAI/data/point_cloud.ply"
  sam_pt_cloud_ply_path: "C:/Users/wai/wAI/data/sam_point_cloud.ply"
  sam3d_model_checkpoint: 'C:/Users/wai/wAI/3D-processing/modelling/sam-3d-body/checkpoints/sam-3d-body-dinov3/model.ckpt'
  mhr_model_checkpoint: 'C:/Users/wai/wAI/3D-processing/modelling/sam-3d-body/checkpoints/sam-3d-body-dinov3/assets/mhr_model.pt'

camera:
  fx: 638.19
  fy: 639.70
  cx: 356.18
  cy: 246.72323964

inputs:
  sex: "Female" # "Female" or "Male"
  height: 155 # in cm, optional
