name: Auto assign reviewers

on:
  pull_request:
    branches:
      - main 

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign reviewers
        uses: peter-evans/auto-assign@v2
        with:
          reviewers: 'mackenziesnyder,adeleyounis,alexisbader,gavin2178'
          remove-reviewers: false
          add-assignees: author
          github-token: ${{ secrets.GITHUB_TOKEN }}

