name: Auto assign reviewers

on:
  pull_request:
    branches:
      - main

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          addReviewers: true
          reviewers: 'mackenziesnyder,adeleyounis,alexisbader,gavin2178'
          numberOfReviewers: 4

