name: Require at least 1 approval

on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  require-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approved = reviews.some(r => r.state === 'APPROVED');
            if (!approved) {
              core.setFailed("PR targeting main has no approvals! At least one reviewer must approve before merge.");
            }